# This file was generated by GoReleaser. DO NOT EDIT.
cask "lstk" do
  version "0.5.8"

  on_macos do
    on_intel do
      sha256 "1b41aff45cf1c72a76a73a369bf648943f393356895223745ec7243e97f9372d"
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/localstack/lstk"
    end
    on_arm do
      sha256 "926b68ae462c66122b1b39b2c9d39af2d234b83f198951f470adafddb7deaabb"
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/localstack/lstk"
    end
  end

  on_linux do
    on_intel do
      sha256 "81be0dabb69cbc6f1fd010126e8664f95ca14bad7776036228306d88df24807f"
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_linux_amd64.tar.gz",
        verified: "github.com/localstack/lstk"
    end
    on_arm do
      sha256 "36c230adef16661f4331214bae1d00620fb4f371dc7f4e6971794a27ae880181"
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/localstack/lstk"
    end
  end

  name "lstk"
  desc "LocalStack CLI v2 - Start and manage LocalStack emulators"
  homepage "https://github.com/localstack/lstk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lstk"
  bash_completion "completions/lstk.bash"
  fish_completion "completions/lstk.fish"
  zsh_completion "completions/lstk.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lstk"]
    end
  end

  # No zap stanza required

end
