# This file was generated by GoReleaser. DO NOT EDIT.
cask "lstk" do
  name "lstk"
  desc "LocalStack CLI v2 - Start and manage LocalStack emulators"
  homepage "https://github.com/localstack/lstk"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lstk"
  bash_completion "completions/lstk.bash"
  zsh_completion "completions/lstk.zsh"
  fish_completion "completions/lstk.fish"

  on_macos do
    on_intel do
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/localstack/lstk"
      sha256 "7e762ae9340b6a96c16017875e037ba876b2bdfd1dc88287beccff043d3bf8e2"
    end
    on_arm do
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/localstack/lstk"
      sha256 "7db6fcde85355b496ec8cafd9b336e6e1df83c280039d62936bb317079374cfa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_linux_amd64.tar.gz",
        verified: "github.com/localstack/lstk"
      sha256 "e852e9dfb306206f8d76bbeba0101785c5017ed628d78a33d479f6ce7b94a991"
    end
    on_arm do
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/localstack/lstk"
      sha256 "34057b5ad2dc9d17bafeccec643d328ca6cc317c8add6b616a774e5d46c8d63f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lstk"]
    end
  end

  # No zap stanza required
end
