# This file was generated by GoReleaser. DO NOT EDIT.
cask "lstk" do
  name "lstk"
  desc "LocalStack CLI v2 - Start and manage LocalStack emulators"
  homepage "https://github.com/localstack/lstk"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lstk"
  bash_completion "completions/lstk.bash"
  zsh_completion "completions/lstk.zsh"
  fish_completion "completions/lstk.fish"

  on_macos do
    on_intel do
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/localstack/lstk"
      sha256 "eee85ca7b7821fa2290e5e8789641c122f22ec61776bee477a4452e65cb78343"
    end
    on_arm do
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/localstack/lstk"
      sha256 "f2a61373e5bb1ded73bf13b55a76f050b09ab159c6419da05eee08c2dc157b87"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_linux_amd64.tar.gz",
        verified: "github.com/localstack/lstk"
      sha256 "53ef6cd3ff8200c58b16e8c7389a29d507e7a62d318d97cb008e31eee8e5d0bf"
    end
    on_arm do
      url "https://github.com/localstack/lstk/releases/download/v#{version}/lstk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/localstack/lstk"
      sha256 "5f3d6256cc324f1a213ba54af16093e137c638e50fe0fee2fe5cc36ae6fe8de1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lstk"]
    end
  end

  # No zap stanza required
end
