# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LocalstackCli < Formula
  desc "Localstack cli packaged using pyinstaller"
  homepage "https://github.com/localstack/localstack-cli"
  url "https://github.com/localstack/localstack-cli/archive/refs/tags/v4.14.0.tar.gz"
  version "4.14.0"
  sha256 "988996d5e964215ee1c4906b7bc53d0c8473a696b23b1d0d9fddf977de37fbee"
  license "NOASSERTION"

  on_macos do
    on_intel do
      url "https://github.com/localstack/localstack-cli/releases/download/v4.14.0/localstack-cli-4.14.0-darwin-amd64.tar.gz"
      sha256 "0db5729a4425dd41fc8dd1b3f0919a73737a516a929b210de93c74f5b2cd6710"
    end

    on_arm do
      url "https://github.com/localstack/localstack-cli/releases/download/v4.14.0/localstack-cli-4.14.0-darwin-arm64.tar.gz"
      sha256 "0d3a3ed7e63db30d8285964dfaec756695c23ab9571e7043dca01e624768d796"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/localstack/localstack-cli/releases/download/v4.14.0/localstack-cli-4.14.0-linux-amd64.tar.gz"
      sha256 "49888706ca5c7db3b52b60069eff950f0cfc0c5ff06536289353496d2a6c689f"
    end

    on_arm do
      url "https://github.com/localstack/localstack-cli/releases/download/v4.14.0/localstack-cli-4.14.0-linux-arm64.tar.gz"
      sha256 "19cd2fd6b477a3ce8cf9ff08ddf4b1931411ff3bb4916765f8baf87e01b6dcbc"
    end
  end

  def install
    libexec.install Dir["*"]
        bin.install_symlink libexec/"localstack"
        generate_completions_from_executable(bin/"localstack", "completion")
  end

  test do
    assert_match /LocalStack Command Line Interface/, shell_output("#{bin}/localstack --help", 0)
  end
end
